# docker-compose.yml

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - PORT=${GATEWAY_PORT}
      - AUTH_SERVICE_URL=http://auth-service:${AUTH_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - ./gateway/.env
    depends_on:
      - auth-service
    networks:
      - app-network
    restart: unless-stopped

  auth-service:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - ./authservice/.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  google-service:
    build:
      context: ./googleservice
      dockerfile: Dockerfile
    ports:
      - "${GOOGLE_SERVICE_PORT}:${GOOGLE_SERVICE_PORT}"
    depends_on: 
      mysql: 
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  admin-service: 
    build:
      context: ./adminservice
      dockerfile: Dockerfile
    ports: 
      - "${ADMIN_SERVICE_PORT}:${ADMIN_SERVICE_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    
  user-service:
    build: 
      context: /userservice
      dockerfile: Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      mysql:
        condition: service_healthy 
    networks:
        - app-network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

    restart: unless-stopped

  payment-service:
    build:
      context: ./paymentservice
      dockerfile: Dockerfile
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    depends_on:
      mysql: 
        condition: service_healthy
    networks:
        - app-network
    volumes:
      - ./paymentservice/src/main/resources/application.properties:/app/application.properties  # Mounts properties file.
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
