export const BOOKINGMESSAGE = {
  STRIPE_PAYMENT_ERROR: "Error creating stripe payment intent",
  BOOKING_CREATION_ERROR: "Error creating booking and teaching session",
  BOOKING_RETRIEVAL_ERROR: "Error retrieving parent booking",
  INVALID_REQUEST_BODY: "Invalid request body",
  COURSE_NOT_FOUND: "Course not found",
  PARENT_BOOKINGS_RETRIEVED: "Parent's bookings retrieved successfully",
  USER_ID_REQUIRED: "UserId is required",
  USER_NOT_FOUND: "User not found",
  PAYMENT_SUCCESS: "Payment intent created successfully",
  BOOKING_SUCCESS: "Booking created successfully",
  NOT_CONNECTED: "User is not connected to Stripe",
  CONNECTED: "User is connected to Stripe",
  NOT_COMPLETE_ONBOARDING: "User has not completed onboarding",
};
